services:
  database:
    container_name: postgres-datmsc3
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - C:\Users\conuo\MscDataScience\DAT620-MSC3set\data\postgres\datMSC3:/data/postgres
    env_file: 
      - datmsc3.env